export interface BulletinPost {
  id: string;
  title: string;
  description: string;
  category: 'sig' | 'cmg' | 'play' | 'event' | 'announcement';
  author: string;
  authorRole: string;
  postedAt: string;
  isPinned: boolean;
  ctaText?: string;
  ctaLink?: string;
  icon: string;
}

export const mockBulletinPosts: BulletinPost[] = [
  {
    id: 'post-1',
    title: '🎮 Play @ GovTech: Among Us Tournament!',
    description: 'This Friday 7pm - Who\'s the imposter? Join our monthly Among Us tournament! Teams of 10, multiple rounds, and prizes for the sneakiest imposters and best detectives. Bring your sus energy!',
    category: 'play',
    author: 'Alex Tan',
    authorRole: 'Play @ GovTech Coordinator',
    postedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isPinned: true,
    ctaText: 'Sign Up Now!',
    ctaLink: '#',
    icon: '🎮',
  },
  {
    id: 'post-2',
    title: '🎨 CMG: #MyDeskSetup Challenge',
    description: 'Show off your workspace creativity! Post your desk setup with #MyDeskSetup and stand a chance to win a premium keyboard. Most aesthetic, most chaotic, and most plant-filled setups all win!',
    category: 'cmg',
    author: 'Jamie Lim',
    authorRole: 'CMG Social Media Lead',
    postedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    isPinned: true,
    ctaText: 'Post Your Setup',
    ctaLink: '#',
    icon: '📸',
  },
  {
    id: 'post-3',
    title: '🎸 SIG: Music Jam Session This Saturday',
    description: 'Calling all musicians! The GovTech Music SIG is hosting a jam session this Saturday 2pm at Hive. Bring your instruments (or just your voice). All skill levels welcome - let\'s make some noise!',
    category: 'sig',
    author: 'Marcus Wong',
    authorRole: 'Music SIG Lead',
    postedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    ctaText: 'Join the Jam',
    ctaLink: '#',
    icon: '🎸',
  },
  {
    id: 'post-4',
    title: '🍜 SIG: Hawker Food Tour - Round 3!',
    description: 'The Food Hunters SIG is back! This time we\'re exploring the best laksa in Singapore. Meet at Maxwell Food Centre this Thursday 12pm. Come hungry, leave happy. Max 15 people!',
    category: 'sig',
    author: 'Sarah Chua',
    authorRole: 'Food Hunters SIG',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    ctaText: 'Reserve Your Spot',
    ctaLink: '#',
    icon: '🍜',
  },
  {
    id: 'post-5',
    title: '🎯 Play @ GovTech: Board Game Night',
    description: 'Tired of screens? Join us for analog fun! We\'ve got Codenames, Azul, Ticket to Ride, and more. Wednesday 6pm at the pantry. Snacks and drinks provided. Competitive spirit optional 😄',
    category: 'play',
    author: 'Kevin Ng',
    authorRole: 'Play @ GovTech',
    postedAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    ctaText: 'Count Me In!',
    ctaLink: '#',
    icon: '🎲',
  },
  {
    id: 'post-6',
    title: '📚 SIG: Book Club - "Tomorrow, and Tomorrow, and Tomorrow"',
    description: 'The Reading Squad is discussing this month\'s pick about game developers and friendship. Join us next Tuesday 7pm (virtual) even if you haven\'t finished! No spoilers in the chat.',
    category: 'sig',
    author: 'Rachel Koh',
    authorRole: 'Reading Squad SIG',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    ctaText: 'Join Discussion',
    ctaLink: '#',
    icon: '📚',
  },
  {
    id: 'post-7',
    title: '🎬 CMG: Behind the Scenes - GovTech Stories',
    description: 'Ever wondered what your colleagues do? CMG is producing a fun video series! We\'re looking for people to share their "day in the life" stories. 5 min of fame, free bubble tea.',
    category: 'cmg',
    author: 'Daniel Lee',
    authorRole: 'CMG Content Creator',
    postedAt: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    ctaText: 'Be Featured!',
    ctaLink: '#',
    icon: '🎬',
  },
  {
    id: 'post-8',
    title: '⚽ SIG: Futsal Match - Dev vs Ops',
    description: 'The eternal rivalry continues! Developers vs Operations futsal match this Sunday 9am at Our Tampines Hub. Spectators welcome. Trash talk encouraged. May the best team win (it\'ll be us - Dev Team).',
    category: 'sig',
    author: 'Ryan Poh',
    authorRole: 'Sports SIG Captain',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    ctaText: 'Pick Your Side',
    ctaLink: '#',
    icon: '⚽',
  },
  {
    id: 'post-9',
    title: '🎤 Play @ GovTech: Karaoke Night Returns!',
    description: 'Belt out your favorites! Monthly karaoke night is back. Private room booked for 20 people. Friday 8pm at Teo Heng. From ballads to K-pop, all genres welcome. No judgment zone!',
    category: 'play',
    author: 'Lisa Tan',
    authorRole: 'Play @ GovTech',
    postedAt: new Date(Date.now() - 3.5 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    ctaText: 'Reserve Your Song',
    ctaLink: '#',
    icon: '🎤',
  },
  {
    id: 'post-10',
    title: '🌟 Reminder: Fun Friday - No Meeting Day!',
    description: 'This Friday is Fun Friday! No meetings after 3pm. Use human-first to find spontaneous activities, join a game session, or just chat with colleagues. Let\'s end the week on a high note!',
    category: 'announcement',
    author: 'People & Culture Team',
    authorRole: 'Employee Experience',
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    icon: '🎉',
  },
];
