import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database types (will be generated by Supabase later)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          anonymous_id: string;
          display_name: string;
          real_name: string | null;
          department: string | null;
          created_at: string;
          last_active: string;
          streak_count: number;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      submissions: {
        Row: {
          id: string;
          user_id: string;
          challenge_id: string;
          image_url: string;
          caption: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['submissions']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['submissions']['Insert']>;
      };
      chat_messages: {
        Row: {
          id: string;
          challenge_id: string;
          user_id: string | null;
          message: string;
          is_ai: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['chat_messages']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['chat_messages']['Insert']>;
      };
    };
  };
};
